### ISSUE TITLE
Homepage: The link for "View the guides" button does not work

### ISSUE THREAD

**Issue by Arika-V** [OPENDAP/Website#11]
![Image](https://github.com/OPENDAP/Website/assets/170548569/61c99034-92d6-4fb7-a9cb-11b7eddb6604)

**Comment by Mikejmnez** [comment]
Good Catch. I checked, and the Page url says "tutorials", but there is no content. I think at some point we were planning on adding such material to a page on the website but ultimately decided `tutorials` be an external link. And while learning material (or guides) can be video and interactive tutorials, for now, I will set the button to take us to the [DataAccessTutorials](https://opendap.github.io/documentation/tutorials/DataAccessTutorials.html) that we already using for tutorials.

Once we have more content, we can make a more strategic decision about where all those "guides" live.

**Comment by Mikejmnez** [comment]
Hey @jahattox - I tried changing the behavior of this card on the Homepage. The tutorials are defined with a custom URL (`Appearance/Menu settings`), and so we don't have content on the page itself. I tried but couldn't add a custom URL to the `Card URL` associated with the feature described by Arika above, so that when clicking the bottom takes you to the external link. Currently, the card is correctly associated with "Tutorials" but it takes you to the empty Page instead of the external link. See snapshot below

<img width="450" alt="Screenshot 2024-05-24 at 9 26 34 AM" src="https://github.com/OPENDAP/Website/assets/8241481/42da7c0d-fdf7-43ba-a55f-276a14a977b8">


Is there a way to define somewhere else, or within the cards, a custom URL? I see that "Archives" shows up as a `Card URL option`, but I cannot manually write a URL or modify the one on "Archives"

**Comment by jahattox** [comment]
@Mikejmnez You should now be able to enter a custom URL for the cards in this module

**Comment by Mikejmnez** [comment]
Great! Thanks @jahattox - I was able to put the external link, and now it correctly points to the documentation, which is where the tutorials and other documentations/resources live for now (that may change later).

**Comment by Mikejmnez** [comment]
@jgallagher59701, I made the fix, and is ready for your review/approval :)

**Comment by jgallagher59701** [comment]
Fixed
