### ISSUE TITLE
In the current releases page, links to the RPM files - that actual release - don't work.

### ISSUE THREAD

**Issue by jgallagher59701** [OPENDAP/Website#41]

**Comment by jgallagher59701** [comment]
I copied the most important of the rpm, tgz, war, etc., files to the fylwheel pub directory. 

Still to do: archive the rest, make a README pointing to that archive (S3?) and get the files linked up.

**Comment by jgallagher59701** [comment]
OK, it's done. I checked the links and they all seem to work.

Also, I edited the text on the https://www.opendap.org/software/hyrax-data-server/ page but I'm not sure about the formatting - I think the image looks odd. I might try to change the size a bit.

@Mikejmnez Let me know what you think.

**Comment by Mikejmnez** [comment]
Hey @jgallagher59701 

I clicked on many of the URL and these trigger downloads so that is great. I haven't tried to build hyrax using the binaries, so I am assuming that the downloaded files are complete. 

- I added some features to improve the navigation including an anchor to the download/deployment description referenced at the top of the page (`take me to download options`). 

### **missing text?**:

I was looking at the deployment options, and I am not sure if there is missing text when you get to ``Linux (RHEL-8) Binaries for Hyrax 1.17.0``, in particular in the BES component. Here is a screenshot:

![Image](https://github.com/user-attachments/assets/7167f533-20fc-4bb7-aff8-f38220cd83ed)



Also seen in the screenshot, there is an EDIT written there (OLFS - top of screenshot). Is that part of the description?

**Comment by jgallagher59701** [comment]
The 'EDIT' after 'OLFS' is a typo.

I'll clean up the text under 'BES'

**Comment by jgallagher59701** [comment]
I claim this is fixed
